const techStacks: { [key: string]: string } = {
  babel: "/images/svg/techstacks/babel.svg",
  circleci: "/images/svg/techstacks/circleci.svg",
  ccs: "/images/svg/techstacks/css-3.svg",
  cypress: "/images/svg/techstacks/cypress.svg",
  do: "/images/svg/techstacks/digital-ocean.svg",
  docker: "/images/svg/techstacks/docker-icon.svg",
  figma: "/images/svg/techstacks/figma.svg",
  html5: "/images/svg/techstacks/html-5.svg",
  git: "/images/svg/techstacks/git-icon.svg",
  graphql: "/images/svg/techstacks/graphql.svg",
  mongo: "/images/svg/techstacks/mongodb.svg",
  heroku: "/images/svg/techstacks/heroku-icon.svg",
  jest: "/images/svg/techstacks/jest.svg",
  jquery: "/images/svg/techstacks/jquery.svg",
  nextjs: "/images/svg/techstacks/nextjs.svg",
  nodejs: "/images/svg/techstacks/nodejs-icon.svg",
  redis: "/images/svg/techstacks/redis.svg",
  postgres: "/images/svg/techstacks/postgresql.svg",
  postman: "/images/svg/techstacks/postman-icon.svg",
  redux: "/images/svg/techstacks/redux.svg",
  reactjs: "/images/svg/techstacks/react.svg",
  sass: "/images/svg/techstacks/sass.svg",
  slack: "/images/svg/techstacks/slack-icon.svg",
  sketch: "/images/svg/techstacks/sketch.svg",
  javascript: "/images/svg/techstacks/javascript.svg",
  typescript: "/images/svg/techstacks/typescript-icon.svg",
  webpack: "/images/svg/techstacks/webpack.svg",
};

export default techStacks;
